### ISSUE TITLE
Can you provide a CSV file?

### ISSUE THREAD

**Issue by zxc28404502** [arjunsehajpal/paulball#1]
Well, I saw this project today and felt great, but it can't run because of the lack of csv data, can I ask for the data file? It won't be used commercially, just play it myself.

**Comment by arjunsehajpal** [comment]
Hi,
I have used data from [this repo](https://github.com/martj42/international_results).

**Comment by zxc28404502** [comment]
First of all, I would like to thank you for the data. Secondly I have a small request, can you help me see where the error point of this code is?

I haven't changed the rest of the code, and I'd appreciate it if you could fix my problem


金守越
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arjunsehajpal/paulball"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月10日(星期六) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arjunsehajpal/paulball] Can you provide a CSV file? (Issue #1)





 
Hi,
 I have used data from this repo.

**Comment by zxc28404502** [comment]
First of all, I would like to thank you for the data. Secondly I have a small request, can you help me see where the error point of this code is?

Traceback (most recent call last):
  File "C:\Users\Dominator\Desktop\paulball-master\main.py", line 4, in <module>
    predict_score(home_team="", away_team="")
  File "C:\Users\Dominator\Desktop\paulball-master\paulball\score.py", line 25, in __call__
    self.execute()
  File "C:\Users\Dominator\Desktop\paulball-master\paulball\score.py", line 43, in execute
    "{} {:.2f}-{:.2f} {}".format(
TypeError: unsupported format string passed to Series.__format__

I haven't changed the rest of the code, and I'd appreciate it if you could fix my problem

**Comment by arjunsehajpal** [comment]
Hi,
I am currently still working on this, so this is not finished. To run this, you need to add the names of home and away teams in main.py. And also need to store data in this path:- `data/internationals/results.csv`  from the root directory.

P.S. - The results have been average actually. The issue actually being that not all goals can be counted as equal. For instance, Asian teams like Japan or Iran play against significantly weaker opposition than their South American and European Counterparts. I have tried nullifying that using Rankings data ([available here](https://www.kaggle.com/datasets/cashncarry/fifaworldranking)).

**Comment by zxc28404502** [comment]
I'm just a beginner in python, sorry can't help you do something, but thank you so much for your generosity! The project you did was really great!
